---
- name: Fetch kubeconfig from target to {{ kubeconfig_folder}}/kubeconfig_{{ minikube_profile}}/config
  fetch:
    src: "c:{{ ansible_env.HOMEPATH }}/.kube/config"
    dest: "{{ kubeconfig_folder}}/kubeconfig_{{ minikube_profile}}/"
    flat: yes